export const workspaceExportFormat = 'career-os.workspace-export';
export const workspaceExportVersion = 2;

export const workspaceExportTables = [
  {
    type: 'search_profiles',
    table: 'search_profiles',
    columns: [
      'id',
      'tenant_id',
      'name',
      'hard_constraints',
      'soft_preferences',
      'active',
      'revision',
      'created_at',
      'updated_at',
    ],
    orderBy: ['id'],
  },
  {
    type: 'audit_events',
    table: 'audit_events',
    columns: [
      'id',
      'tenant_id',
      'actor',
      'actor_id',
      'event_type',
      'entity_type',
      'entity_id',
      'summary',
      'created_at',
    ],
    orderBy: ['id'],
  },
  {
    type: 'applications',
    table: 'applications',
    columns: [
      'id',
      'tenant_id',
      'company',
      'role',
      'raw_text',
      'url',
      'accent',
      'stage',
      'revision',
      'create_idempotency_key',
      'create_input_hash',
      'created_at',
      'updated_at',
      'deleted_at',
      'company_sources',
    ],
    orderBy: ['id'],
  },
  {
    type: 'profiles',
    table: 'profiles',
    columns: [
      'id',
      'tenant_id',
      'name',
      'headline',
      'profile_kind',
      'revision',
      'created_at',
      'updated_at',
    ],
    orderBy: ['id'],
  },
  {
    type: 'sources',
    table: 'sources',
    columns: [
      'id',
      'tenant_id',
      'kind',
      'title',
      'locator',
      'trust',
      'sensitivity',
      'allowed_uses',
      'profile_id',
      'position',
    ],
    orderBy: ['id'],
  },
  {
    type: 'claims',
    table: 'claims',
    columns: [
      'id',
      'tenant_id',
      'statement',
      'level',
      'sensitivity',
      'allowed_uses',
      'profile_id',
      'position',
    ],
    orderBy: ['id'],
  },
  {
    type: 'evidence',
    table: 'evidence',
    columns: [
      'id',
      'tenant_id',
      'source_id',
      'label',
      'excerpt',
      'profile_id',
      'position',
    ],
    orderBy: ['id'],
  },
  {
    type: 'claim_evidence',
    table: 'claim_evidence',
    columns: [
      'tenant_id',
      'claim_id',
      'evidence_id',
      'relation',
      'profile_id',
      'position',
    ],
    orderBy: ['claim_id', 'evidence_id'],
  },
  {
    type: 'opportunities',
    table: 'opportunities',
    columns: [
      'id',
      'tenant_id',
      'company',
      'role',
      'raw_text',
      'url',
      'extraction_status',
      'application_id',
      'application_revision',
      'accent',
      'company_sources',
    ],
    orderBy: ['id'],
  },
  {
    type: 'workflow_runs',
    table: 'workflow_runs',
    columns: [
      'id',
      'tenant_id',
      'opportunity_id',
      'state',
      'version',
      'revision_count',
      'status',
      'token_budget',
      'cost_budget_micros',
      'deadline_at',
      'input_hash',
      'used_tokens',
      'used_cost_micros',
      'reserved_tokens',
      'reserved_cost_micros',
      'profile_id',
      'source_profile_id',
      'source_profile_revision',
      'idempotency_key',
      'parent_run_id',
    ],
    orderBy: ['id'],
  },
  {
    type: 'workflow_steps',
    table: 'workflow_steps',
    columns: [
      'id',
      'tenant_id',
      'workflow_run_id',
      'stage',
      'attempt',
      'status',
      'idempotency_key',
      'lease_expires_at',
      'output_artifact_id',
      'created_at',
      'completed_at',
      'input',
      'input_hash',
      'provider',
      'model',
      'reservation_id',
      'dispatched_at',
      'failure_code',
      'page_spec_id',
      'research_source_artifact_id',
    ],
    orderBy: ['id'],
  },
  {
    type: 'workflow_events',
    table: 'workflow_events',
    columns: [
      'id',
      'tenant_id',
      'workflow_run_id',
      'actor',
      'event_type',
      'summary',
      'payload',
      'created_at',
    ],
    orderBy: ['id'],
  },
  {
    type: 'artifacts',
    table: 'artifacts',
    columns: [
      'id',
      'tenant_id',
      'workflow_run_id',
      'kind',
      'version',
      'schema_version',
      'body',
      'created_by',
      'created_at',
    ],
    orderBy: ['id'],
  },
  {
    type: 'run_budget_reservations',
    table: 'run_budget_reservations',
    columns: [
      'id',
      'tenant_id',
      'workflow_run_id',
      'idempotency_key',
      'requested_tokens',
      'requested_cost_micros',
      'lease_expires_at',
      'status',
      'actual_tokens',
      'actual_cost_micros',
      'created_at',
      'finished_at',
    ],
    orderBy: ['id'],
  },
  {
    type: 'model_usage',
    table: 'model_usage',
    columns: [
      'id',
      'tenant_id',
      'workflow_run_id',
      'actor',
      'provider',
      'model',
      'input_tokens',
      'output_tokens',
      'cost_micros',
      'latency_ms',
      'cache_hit',
      'created_at',
      'workflow_step_id',
      'usage_basis',
      'provider_request_id',
    ],
    orderBy: ['id'],
  },
  {
    type: 'strategy_approvals',
    table: 'strategy_approvals',
    columns: [
      'id',
      'tenant_id',
      'workflow_run_id',
      'strategy_artifact_id',
      'strategy_artifact_hash',
      'idempotency_key',
      'approved_by',
      'created_at',
    ],
    orderBy: ['id'],
  },
  {
    type: 'page_specs',
    table: 'page_specs',
    columns: [
      'id',
      'tenant_id',
      'workflow_run_id',
      'version',
      'spec',
      'input_hash',
      'spec_hash',
      'invalidated_at',
      'source_artifact_id',
    ],
    orderBy: ['id'],
  },
  {
    type: 'page_spec_claims',
    table: 'page_spec_claims',
    columns: ['tenant_id', 'page_spec_id', 'claim_id'],
    orderBy: ['page_spec_id', 'claim_id'],
  },
  {
    type: 'page_spec_evidence',
    table: 'page_spec_evidence',
    columns: [
      'tenant_id',
      'page_spec_id',
      'claim_id',
      'evidence_id',
      'position',
    ],
    orderBy: ['page_spec_id', 'claim_id', 'position', 'evidence_id'],
  },
  {
    type: 'review_starts',
    table: 'review_starts',
    columns: [
      'id',
      'tenant_id',
      'workflow_run_id',
      'page_spec_id',
      'page_spec_hash',
      'page_spec_artifact_id',
      'page_spec_artifact_hash',
      'idempotency_key',
      'started_by',
      'created_at',
    ],
    orderBy: ['id'],
  },
  {
    type: 'reviews',
    table: 'reviews',
    columns: [
      'id',
      'tenant_id',
      'page_spec_id',
      'reviewer',
      'verdict',
      'issues',
      'page_spec_hash',
      'workflow_run_id',
      'workflow_step_id',
      'output_artifact_id',
    ],
    orderBy: ['id'],
  },
  {
    type: 'review_issue_decisions',
    table: 'review_issue_decisions',
    columns: [
      'id',
      'tenant_id',
      'workflow_run_id',
      'page_spec_id',
      'review_id',
      'issue_index',
      'issue_text',
      'decision',
      'corrected_run_id',
      'decided_by',
      'idempotency_key',
      'input_hash',
      'created_at',
    ],
    orderBy: ['id'],
  },
  {
    type: 'approvals',
    table: 'approvals',
    columns: [
      'id',
      'tenant_id',
      'page_spec_id',
      'approved_by',
      'approved_at',
      'page_spec_hash',
    ],
    orderBy: ['id'],
  },
  {
    type: 'publications',
    table: 'publications',
    columns: [
      'id',
      'tenant_id',
      'page_spec_id',
      'published_at',
      'revoked_at',
      'page_spec_hash',
      'publication_payload',
    ],
    orderBy: ['id'],
  },
  {
    type: 'share_links',
    table: 'share_links',
    columns: ['id', 'tenant_id', 'publication_id', 'expires_at', 'revoked_at'],
    orderBy: ['id'],
  },
  {
    type: 'url_import_attempts',
    table: 'url_import_attempts',
    columns: [
      'id',
      'tenant_id',
      'actor_id',
      'status',
      'created_at',
      'finished_at',
    ],
    orderBy: ['id'],
  },
] as const;

export const workspaceExportExclusions = [
  'Authentication credentials, provider tokens, password hashes, sessions and verification secrets.',
  'Raw private-link capabilities and their token hashes.',
  'Worker ownership identifiers and global heartbeats.',
  'Browser-only drafts, caches and raw files that were never submitted to the server.',
] as const;
